

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './:/product-register'
    environment:
      - 'DATABASE_USER=postgres'
      - 'DATABASE_PASSWORD=postgres'
      - 'DATABASE_HOST=db'
      - 'DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
